# permissions for end users to edit mutationinjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ng-porch
    app.kubernetes.io/managed-by: kustomize
  name: mutationinjector-editor-role
rules:
- apiGroups:
  - ng.porch.kpt.dev
  resources:
  - mutationinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ng.porch.kpt.dev
  resources:
  - mutationinjectors/status
  verbs:
  - get
