# permissions for end users to edit packagevariants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ng
    app.kubernetes.io/managed-by: kustomize
  name: packagevariant-editor-role
rules:
- apiGroups:
  - ng.porch.kpt.dev
  resources:
  - packagevariants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ng.porch.kpt.dev
  resources:
  - packagevariants/status
  verbs:
  - get
