---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ng.porch.kpt.dev
  resources:
  - mutationinjectors
  - packagevariants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ng.porch.kpt.dev
  resources:
  - mutationinjectors/finalizers
  - packagevariants/finalizers
  verbs:
  - update
- apiGroups:
  - ng.porch.kpt.dev
  resources:
  - mutationinjectors/status
  - packagevariants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions/approval
  verbs:
  - get
  - patch
  - update
